#!/bin/bash
while IFS= read -r file; do
	echo $file
	filename=${file##*/}
	filename=${filename% -*}
	season=${filename##*-}
	season=${season:2:2}
	filename=${filename% -*}
	location=$(find /mnt/stultnas/Tobin/ -type d -name "$filename")
	mv "$file" "${location}/Season ${season}"
done < <(find /mnt/stultnas/Tobin/Converted -type f)
