#!/bin/bash
while IFS= read -r file; do
	filename=${file##*/}
	filename=${filename%.*}
	folder=${filename% -*}
	season=${folder##*-}
	season=${season:2:2}
	folder=${folder% -*}
	location=$(find /mnt/stultnas/Tobin/ -type d -name "$folder")
	find "${location}/Season ${season}/" -type f -name "${filename}*" -delete
	echo "Removed ${filename}"
	mv "$file" "${location}/Season ${season}"
	echo "Moved $file"
done < <(find /mnt/stultnas/Tobin/Converted -type f)
