#!/usr/bin/env bash
action="$1"
case "$action" in
   suspend|hibernate) stuff ;;
   resume|thaw)       sleep 30 && sshfs -o IdentityFile=~/.ssh/id_rsa stultiensnas@192.168.178.31:/ /mnt/stultnas &>> /home/tobins/Projects/Shell/nas/log.txt;;
esac
