#!/bin/sh

overlay=/usr/share/pixmaps/lockoverlay.png

scrot -o /tmp/currentworkspace.png
convert /tmp/currentworkspace.png -blur 0x5 /tmp/currentworkspaceblur.png
xset s on
if [ -f "$overlay" ]; then
	composite -gravity southeast $overlay /tmp/currentworkspaceblur.png /tmp/lockbackground.png
	i3lock -i /tmp/lockbackground.png -n; xset s off -dpms
else
	i3lock -i /tmp/currentworkspaceblur.png -n; xset s off -dpms
fi
