#!/bin/sh

has_n_option=false
while getopts :n opt; do
    case $opt in 
        n) has_n_option=true ;;
    esac
done

declare -A g bmarray;

while IFS=\| read -r guid date id url title tags;
do
  bookmark="$title "-" "$url" "-" "$tags"";
  bmarray["$bookmark"]="$url";
done < ~/bm.lnk

function load() {
  while IFS=\| read -r guid date id url title tags;
  do
    bookmark="$title "-" "$url" "-" "$tags"";
    printf "$bookmark\n";
	done < ~/bm.lnk
  printf
}

choice=$(load | dmenu -i -l 15 -p "Add/Open bookmark:")

if [[ ! -z "$choice" ]]; then
	if $has_n_option; then
		case "$choice" in
			Add) dmenu-bm-add ;;
 			*) $BROWSER --new-window ${bmarray[$choice]} ;;
		esac
	else
		case "$choice" in
  		Add) dmenu-bm-add ;;
 			*) $BROWSER ${bmarray[$choice]} ;;
		esac
	fi
fi
