#!/bin/sh

todoist-cli sync
tasks=$(todoist-cli l --filter today | grep "00:00" | wc -l)
if [ "$tasks" -ne "0" ];then
  notify-send 'Tasks left' 'You have '$tasks' left for today.' --icon=dialog-information
fi
